spring:
  application:
    name: Payment Gateway Proxy

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: never

---
spring:
  config:
    activate:
      on-profile: default

backend:
  url: "http://localhost:8080/payments"

proxy:
  concurrency:
    start: 2048
    max: 65535
    unpause-delay: 20
    busy-wait-interval: 20
    scale-up-interval: 50
    scale-down-interval: 100
    backpressure-handler: simple

response:
  timeout: 30000
