spring:
  application:
    name: Payment Gateway Proxy

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: never

---
spring:
  config:
    activate:
      on-profile: default

backend:
  url: "http://localhost:8080/payments"

proxy:
  concurrency:
    start: 64
    max: 10000
    unpause-delay: 20
    scale-up-interval: 500
    scale-down-interval: 250
    backpressure-handler: simple

response:
  timeout: 30000
