spring:
  application:
    name: Payment Gateway Proxy

management:
  endpoint:
    health:
      show-details: never

---
spring:
  config:
    activate:
      on-profile: local

backend:
  url: "http://localhost:8081/payments"

proxy:
  concurrency:
    start: 64
    max: 128
    unpause-delay: 200
    busy-wait-interval: 20
    modifiable-interval: 30000

